services:
  db:
    container_name: "db"
    image: postgres:16.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  app:
    container_name: "app"
    build: .
    env_file: .env
    depends_on:
      - db
